In [21]:
import numpy as np

def main():
    some_random_matrix = generate_some_random_matrix(4, 5)

    modify_matrix(some_random_matrix)

    print("The modified matrix is:")
    print(some_random_matrix)

def generate_some_random_matrix(rows, cols):
    return np.random.uniform(1, 20, size=(rows, cols))

def modify_matrix(matrix):
    matrix[np.arange(matrix.shape[0]), matrix.argmax(axis=1)] = 0

if __name__ == "__main__":
    main()



The modified matrix is:
[[ 2.97338284  0.         14.35491124 14.67605105  5.73011488]
 [14.20833692  1.51964859 10.9654228   1.50984552  0.        ]
 [ 7.21074277  6.58002114  2.76474339  0.         10.40459201]
 [14.49794608 15.81802328 13.5445712   0.          2.23160703]]
